loopback_users.guest = false

default_user = chaos_user
default_pass = chaos_password

default_vhost = /


default_permissions.configure = .*
default_permissions.read = .*
default_permissions.write = .*


listeners.tcp.default = 5672


management.listener.port = 15672
management.listener.ssl = false